/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as AppPassRouteImport } from './routes/app/pass'
import { Route as DriversIndexRouteImport } from './routes/drivers/index'
import { Route as DriversSignupRouteImport } from './routes/drivers/signup'
import { Route as OperatorsIndexRouteImport } from './routes/operators/index'
import { Route as OperatorsCalculatorRouteImport } from './routes/operators/calculator'
import { Route as OperatorsSignupRouteImport } from './routes/operators/signup'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminOperatorPortalRouteImport } from './routes/_admin/operator/portal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPassRoute = AppPassRouteImport.update({
  id: '/app/pass',
  path: '/app/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversSignupRoute = DriversSignupRouteImport.update({
  id: '/drivers/signup',
  path: '/drivers/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsIndexRoute = OperatorsIndexRouteImport.update({
  id: '/operators/',
  path: '/operators/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsCalculatorRoute = OperatorsCalculatorRouteImport.update({
  id: '/operators/calculator',
  path: '/operators/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsSignupRoute = OperatorsSignupRouteImport.update({
  id: '/operators/signup',
  path: '/operators/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperatorPortalRoute = AdminOperatorPortalRouteImport.update({
  id: '/operator/portal',
  path: '/operator/portal',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investors': typeof InvestorsRoute
  '/app/pass': typeof AppPassRoute
  '/drivers/signup': typeof DriversSignupRoute
  '/operators/calculator': typeof OperatorsCalculatorRoute
  '/operators/signup': typeof OperatorsSignupRoute
  '/drivers/': typeof DriversIndexRoute
  '/operators/': typeof OperatorsIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/operator/portal': typeof AdminOperatorPortalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investors': typeof InvestorsRoute
  '/app/pass': typeof AppPassRoute
  '/drivers/signup': typeof DriversSignupRoute
  '/operators/calculator': typeof OperatorsCalculatorRoute
  '/operators/signup': typeof OperatorsSignupRoute
  '/drivers': typeof DriversIndexRoute
  '/operators': typeof OperatorsIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/operator/portal': typeof AdminOperatorPortalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/investors': typeof InvestorsRoute
  '/app/pass': typeof AppPassRoute
  '/drivers/signup': typeof DriversSignupRoute
  '/operators/calculator': typeof OperatorsCalculatorRoute
  '/operators/signup': typeof OperatorsSignupRoute
  '/drivers/': typeof DriversIndexRoute
  '/operators/': typeof OperatorsIndexRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/operator/portal': typeof AdminOperatorPortalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investors'
    | '/app/pass'
    | '/drivers/signup'
    | '/operators/calculator'
    | '/operators/signup'
    | '/drivers/'
    | '/operators/'
    | '/admin/dashboard'
    | '/operator/portal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/investors'
    | '/app/pass'
    | '/drivers/signup'
    | '/operators/calculator'
    | '/operators/signup'
    | '/drivers'
    | '/operators'
    | '/admin/dashboard'
    | '/operator/portal'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/investors'
    | '/app/pass'
    | '/drivers/signup'
    | '/operators/calculator'
    | '/operators/signup'
    | '/drivers/'
    | '/operators/'
    | '/_admin/admin/dashboard'
    | '/_admin/operator/portal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InvestorsRoute: typeof InvestorsRoute
  AppPassRoute: typeof AppPassRoute
  DriversSignupRoute: typeof DriversSignupRoute
  OperatorsCalculatorRoute: typeof OperatorsCalculatorRoute
  OperatorsSignupRoute: typeof OperatorsSignupRoute
  DriversIndexRoute: typeof DriversIndexRoute
  OperatorsIndexRoute: typeof OperatorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pass': {
      id: '/app/pass'
      path: '/app/pass'
      fullPath: '/app/pass'
      preLoaderRoute: typeof AppPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/signup': {
      id: '/drivers/signup'
      path: '/drivers/signup'
      fullPath: '/drivers/signup'
      preLoaderRoute: typeof DriversSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/': {
      id: '/operators/'
      path: '/operators'
      fullPath: '/operators/'
      preLoaderRoute: typeof OperatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/calculator': {
      id: '/operators/calculator'
      path: '/operators/calculator'
      fullPath: '/operators/calculator'
      preLoaderRoute: typeof OperatorsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/signup': {
      id: '/operators/signup'
      path: '/operators/signup'
      fullPath: '/operators/signup'
      preLoaderRoute: typeof OperatorsSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/operator/portal': {
      id: '/_admin/operator/portal'
      path: '/operator/portal'
      fullPath: '/operator/portal'
      preLoaderRoute: typeof AdminOperatorPortalRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminOperatorPortalRoute: typeof AdminOperatorPortalRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminOperatorPortalRoute: AdminOperatorPortalRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InvestorsRoute: InvestorsRoute,
  AppPassRoute: AppPassRoute,
  DriversSignupRoute: DriversSignupRoute,
  OperatorsCalculatorRoute: OperatorsCalculatorRoute,
  OperatorsSignupRoute: OperatorsSignupRoute,
  DriversIndexRoute: DriversIndexRoute,
  OperatorsIndexRoute: OperatorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
